- id: check-eol
  name: Check supported Python EOL
  entry: checkeol
  language: python
  files: '^pyproject.toml$'
  types: [toml]

- id: check-eol-cached
  name: Check supported Python EOL (cache only)
  entry: checkeol --cache_only
  language: python
  files: '^pyproject.toml$'
  types: [toml]
